# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_data',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_directions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images/'),
        ),
    ]
