# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_directions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.TextField(),
        ),
    ]
