# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20190312_2117'),
        ('meal', '0007_recipe_slug'),
    ]

    operations = [
    ]
