# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_merge_20190314_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_images/bolognese.jpg', upload_to='recipe_images/'),
        ),
    ]
