# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_auto_20190318_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.UserProfile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='bolognese.jpg', upload_to='uploaded_images/'),
        ),
    ]
