# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_auto_20190319_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='bolognese.jpg', upload_to='uploaded_image/'),
        ),
    ]
