# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0011_auto_20190319_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='bolognese.jpg', upload_to='uploaded_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meal.Recipe'),
        ),
    ]
