# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0012_auto_20190319_1314'),
        ('meal', '0012_auto_20190319_1326'),
    ]

    operations = [
    ]
