# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import meal.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0013_merge_20190319_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='bolognese.jpg', upload_to=meal.models._get_upload_path),
        ),
    ]
