# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import meal.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0016_auto_20190319_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='<function _get_upload_path at 0x7f6678e7e0d0>/brownies.jpg', upload_to=meal.models._get_upload_path),
        ),
    ]
