# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0018_auto_20190319_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='uploaded_images'),
        ),
    ]
