# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0020_auto_20190319_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default='bolgnese.jpg', null=True, upload_to='uploaded_images'),
        ),
    ]
