# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import meal.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0021_auto_20190319_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default='bolgnese.jpg', null=True, upload_to=meal.models._get_upload_path),
        ),
    ]
