# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meal.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0022_auto_20190319_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='bolognese.jpg', upload_to=meal.models._get_upload_path),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meal.Recipe'),
        ),
    ]
