# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0023_auto_20190319_1716'),
        ('meal', '0014_auto_20190319_1540'),
    ]

    operations = [
    ]
