# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0025_auto_20190319_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
