# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0024_merge_20190319_1738'),
        ('meal', '0025_auto_20190319_1742'),
    ]

    operations = [
    ]
