# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0027_userprofile_created'),
        ('meal', '0026_merge_20190319_1752'),
    ]

    operations = [
    ]
