# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0027_userprofile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeprofile',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='RecipeProfile',
        ),
    ]
