# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0028_auto_20190320_1339'),
        ('meal', '0028_merge_20190320_1138'),
    ]

    operations = [
    ]
