# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0025_auto_20190319_2107'),
        ('meal', '0015_like'),
        ('meal', '0029_merge_20190320_1354'),
    ]

    operations = [
    ]
