# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0032_auto_20190321_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
